version: '2'

volumes:
    pulse:                          # Required for PA over UNIX socket
    weston:
    userData:

services:
  wifi-connect:
    build: ./wifi-connect
    network_mode: "host"
    labels:
      io.balena.features.dbus: '1'
    cap_add:
      - NET_ADMIN
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
        
  audio:
    image: balenablocks/audio
    privileged: true
    volumes:
      - 'pulse:/run/pulse'

  weston:
    restart: always
    build: ./weston
    privileged: true
    volumes:
      - 'weston:/run/weston'

  wpe:
    restart: always
    build: ./wpe
    privileged: true
    ports:
      - 8080:8080
      - 12321:12321
    volumes:
      - 'weston:/run/weston'
      - 'pulse:/run/pulse'
      - 'userData:/data'

